name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: ESLint Plus
    # You may pin to the exact commit or the version.
    # uses: bradennapier/eslint-plus-action@972d934f4b5b41945c4f489dc49717c80eb8be4c
      uses: bradennapier/eslint-plus-action@v3.4.2
      with:
        # By setting this to "false", only errors will be annotated
        reportWarnings: true
        npmInstall: true
    - uses: pre-commit/action@v2.0.0
